/*
 * @Description:
 * @Date: 2021-09-17 15:48:56
 * @LastEditTime: 2021-09-22 11:04:12
 * @FilePath: \mds\src\views\mds\components\button\code.js
 * @Author: Devin
 */
export default {
  code_built_in: `<pre class="language-markup" contenteditable="false" data-mce-selected="1">  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>CcButton</span><span class="token punctuation">&gt;</span></span>添加<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>CcButton</span><span class="token punctuation">&gt;</span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>CcButton</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>basic<span class="token punctuation">"</span></span><span class="token punctuation">&gt;</span></span>取消性质按钮<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>CcButton</span><span class="token punctuation">&gt;</span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>CcButton</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>text<span class="token punctuation">"</span></span><span class="token punctuation">&gt;</span></span>文字按钮<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>CcButton</span><span class="token punctuation">&gt;</span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>CcButton</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>textAdd<span class="token punctuation">"</span></span><span class="token punctuation">&gt;</span></span>添加<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>CcButton</span><span class="token punctuation">&gt;</span></span>﻿</pre>`,
  code_2: `<pre class=" language-markup" contenteditable="false" data-mce-selected="1">  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>CcButton</span> <span class="token attr-name">disabled</span><span class="token punctuation">&gt;</span></span>禁用按钮<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>CcButton</span><span class="token punctuation">&gt;</span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>CcButton</span> <span class="token attr-name">disabled</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>basic<span class="token punctuation">"</span></span><span class="token punctuation">&gt;</span></span>禁用取消性质按钮<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>CcButton</span><span class="token punctuation">&gt;</span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>CcButton</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>text<span class="token punctuation">"</span></span> <span class="token attr-name">disabled</span><span class="token punctuation">&gt;</span></span>文字按钮<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>CcButton</span><span class="token punctuation">&gt;</span></span></pre>`
};
