/*
 * @Description:
 * @Date: 2021-09-17 15:48:56
 * @LastEditTime: 2021-09-22 14:42:59
 * @FilePath: \mds\src\views\mds\components\message_box\code.js
 * @Author: Devin
 */
export default {
  code: `<pre class="language-javascript" contenteditable="false" data-mce-selected="1">  <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">$cc_message_confirm</span><span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=&gt;</span> <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">$cc_message</span><span class="token punctuation">(</span><span class="token string">'这是确定的回调'</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=&gt;</span> <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">$cc_message</span><span class="token punctuation">(</span><span class="token string">'这是取消的回调'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">$cc_message_alert</span><span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=&gt;</span> <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">$cc_message</span><span class="token punctuation">(</span><span class="token string">'这是确定的回调'</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=&gt;</span> <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">$cc_message</span><span class="token punctuation">(</span><span class="token string">'这是取消的回调'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>﻿</pre>`
};
